### PR TITLE
package: engine, bump to the oldest LTS

### PR DESCRIPTION
**Pull request by fredericosilva**

### CODE REVIEW

**Comment by bodrovis** [comment]
@beinarovic Thoughts? I'm a bit hesitant to accept this as some people might still be on Node 10 and this library works perfectly fine with this version... Not sure.

**Comment by fredericosilva** [comment]
I did raise this after noticing that node 10 and 11 are no longer being tested.

7.0.1 (10-Nov-2021)
- ... remove Node 11 from test matrix (EOL)

6.2.1 (18-May-21)
- Do not test with Node 10 that has reached its EOL

**Comment by bodrovis** [comment]
Well, yeah, that's right. But still Node <11 is supported unofficially :) Ideally, we need to understand whether our customers are still using these older versions. So let us discuss internally. At any rate, thank you for the input and showing interest to this solution!

**Comment by bodrovis** [comment]
We decided to keep things as is for now. It's hard to asses how many customers are still using older Node so it would be safe to retain the current version. Perhaps, we should bump the engine version some time in 2022. Thank you!

**Pull request closed without merging**
